#nombre asignado al workflow
name: Deploy to server 

#accion en la que se activara el deploy
on: push

#tareas a realizar
jobs: 
    first_jobs:
        runs-on: ubuntu-latest
 
        steps:
            - name: Hola mundo
              run: echo "Hola mundo"

    second_jobs:
        ##needs: genera una dependencia, necesita ejecutar primero first_jobs para posteriormente ejecutar secod_jobs.
        needs: first_jobs
        runs-on: ubuntu-latest
 
        steps:
            - name: Hola mundo
              run: echo "Hola mundo segundo "